### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Droniu** [cozyGalvinism/saleor-app-rust-axum#1]
Hello @cozyGalvinism, would it be possible for you to add a license to this project? We're considering adding this repository to community examples in Saleor docs.

**Comment by cozyGalvinism** [comment]
Hello, I've added the Apache 2.0 license to the project in b3aac35. I hope that helps!

**Comment by Droniu** [comment]
Thanks a lot. We included your project in our docs section:
https://docs.saleor.io/developer/extending/apps/developing-apps/app-examples
